# Generated by Django 2.1.2 on 2018-10-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='list_priority',
            field=models.IntegerField(),
        ),
    ]
