# Generated by Django 2.1.2 on 2018-10-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20181004_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['list_priority']},
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='item_title',
            field=models.CharField(max_length=200),
        ),
    ]
