# Generated by Django 2.1.2 on 2018-10-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20181002_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='list_items',
        ),
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
