# Generated by Django 2.1.2 on 2018-10-02 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20181002_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='item_list',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='item_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='todolist',
            name='list_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list', to='todolist.TodoItem'),
        ),
    ]
