# Generated by Django 2.1.2 on 2018-10-02 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_auto_20181002_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['due']},
        ),
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['list_priority'], 'verbose_name': 'TodoItem', 'verbose_name_plural': 'TodoItems'},
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='list_items',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='published_date',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='item_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='todolist.TodoList'),
        ),
    ]
